title: Paul Darnaby # your name (or website title) here
logo: "/Professional Photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I’m a data professional with a Master’s in Analytics from Georgia Tech and a passion for applying data science to real-world problems — from optimizing business performance to analyzing energy usage and training data. I use Python, SQL, and Tableau to build scalable data pipelines, develop dashboards, and train machine learning models that deliver actionable insights. Whether I’m building predictive tools or uncovering new ways to extract meaning from data, I’m driven by curiosity, clarity, and continuous improvement — in work and in life.  <br><br>
  <a href="https://www.linkedin.com/in/pauldarnaby/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
